# Generated by Django 5.1.3 on 2024-11-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_realestateproperty_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateproperty',
            name='image',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
