# Generated by Django 5.1.3 on 2024-11-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_realestateproperty_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestateproperty',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='realestateproperty',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
