# Generated by Django 5.1.3 on 2024-11-19 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
